workspace:
  base: /drone
  path: src

pipeline:
  tests:
    image: python:3.5

    environment:
      - POSTGRES_USER=mhackspace
      - USE_DOCKER=yes
      - DJANGO_SETTINGS_MODULE=config.settings.test
    commands:
      - echo $DRONE_BUILD_DIR
      - echo $WORKSPACE
      - cp -n env.example .env
      - ls -la /drone/src/
      - ls -la /drone/src/requirements/
      - pip install -r ./requirements/test.txt
      - python manage.py test mhackspace --verbosity 2

services:
  mailhog:
    image: mailhog/mailhog
