pipeline:
  backend:
    image: maidstonehackspacewebsite_django
    environment:
      - POSTGRES_USER=mhackspace
      - USE_DOCKER=yes
      - DJANGO_SETTINGS_MODULE=config.settings.test
    commands:
      - cp -n env.example .env
      - python manage.py test mhackspace --verbosity 2

  deploy:



#volumes:
#  postgres_data_dev: {}
#  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
#    volumes:
#      - postgres_data_dev:/var/lib/postgresql/data
#      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=mhackspace

#  django:
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile-dev
#    command: /start-dev.sh
#    depends_on:
#      - postgres
#    environment:
#      - POSTGRES_USER=mhackspace
#      - USE_DOCKER=yes
#    volumes:
#      - .:/app
#    ports:
#      - "8180:8000"
#    links:
#      - postgres
#      - mailhog

  mailhog:
    image: mailhog/mailhog

deploy:
  ssh:
    target: test.maidstone-hackspace.org.uk:/var/www/test-maidstone-hackspace.org.uk 22
    artifacts:
      - build.result
      - config/file
    cmd: /opt/bin/redeploy.sh
