pipeline:
  tests:
    image: python:3.5

    environment:
      - POSTGRES_USER=mhackspace
      - USE_DOCKER=yes
      - DJANGO_SETTINGS_MODULE=config.settings.test
    commands:
      - cp -n env.example .env
      - pip install -r /drone/src/requirements/test.txt
      - python manage.py test mhackspace --verbosity 2

  mailhog:
    image: mailhog/mailhog
