version: '2'

volumes:
  gunicorn_socket: {}
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - USE_DOCKER=yes
    volumes:
      - .:/app
      - gunicorn_socket:/var/run/gunicorn/
    ports:
      - "8180:8000"
    links:
      - postgres
      - mailhog

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    environment:
      - MY_DOMAIN_NAME=maidstone-hackspace.org.uk
    ports:
      - "0.0.0.0:80:80"
      # - "0.0.0.0:443:443"
    volumes:
      - gunicorn_socket:/var/run/gunicorn/

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8125:8025"

  redis:
    image: redis:latest
